artifact_uri: file:///C:/Users/Home/PycharmProjects/Basic projects/mlops-assignment-1/src/mlruns_iris/148731765894909086/fa396f4f0d894117be3b30ab37398b63/artifacts
end_time: 1758140667474
entry_point_name: ''
experiment_id: '148731765894909086'
lifecycle_stage: active
run_id: fa396f4f0d894117be3b30ab37398b63
run_name: KNN
source_name: ''
source_type: 4
source_version: ''
start_time: 1758140663528
status: 3
tags: []
user_id: Home
