artifact_location: file:///C:/Users/Home/PycharmProjects/Basic projects/mlops-assignment-1/mlruns_iris/825080163418872201
creation_time: 1758141178532
experiment_id: '825080163418872201'
last_update_time: 1758141178532
lifecycle_stage: active
name: iris_models
