name: CI/CD Pipeline
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        # Stop if there are Python syntax errors or undefined names
        flake8 src/ --count --select=E9,F63,F7,F82 --show-source --statistics
    - name: Verify Training Script Runs
      run: |
        # We run the script to make sure it doesn't crash
        python src/train.py
    - name: Run Unit Tests
      run: |
        pytest tests/