artifact_uri: file:///C:/Users/Home/PycharmProjects/Basic projects/mlops-assignment-1/src/mlruns_iris/148731765894909086/081a5d9845ee4a749db46efd761e53c0/artifacts
end_time: 1758140494876
entry_point_name: ''
experiment_id: '148731765894909086'
lifecycle_stage: active
run_id: 081a5d9845ee4a749db46efd761e53c0
run_name: SVM
source_name: ''
source_type: 4
source_version: ''
start_time: 1758140491530
status: 3
tags: []
user_id: Home
