artifact_uri: file:///C:/Users/Home/PycharmProjects/Basic projects/mlops-assignment-1/src/mlruns_iris/148731765894909086/c8d9ffe6501c4c6491a2186a7dae4494/artifacts
end_time: 1758140491518
entry_point_name: ''
experiment_id: '148731765894909086'
lifecycle_stage: active
run_id: c8d9ffe6501c4c6491a2186a7dae4494
run_name: Logistic_Regression
source_name: ''
source_type: 4
source_version: ''
start_time: 1758140486219
status: 3
tags: []
user_id: Home
