artifact_uri: file:///C:/Users/Home/PycharmProjects/Basic projects/mlops-assignment-1/src/mlruns_iris/148731765894909086/faf958e2e8c649f1b0644227a1fe4ccd/artifacts
end_time: 1758140498269
entry_point_name: ''
experiment_id: '148731765894909086'
lifecycle_stage: active
run_id: faf958e2e8c649f1b0644227a1fe4ccd
run_name: KNN
source_name: ''
source_type: 4
source_version: ''
start_time: 1758140494888
status: 3
tags: []
user_id: Home
