artifact_uri: file:///C:/Users/Home/PycharmProjects/Basic projects/mlops-assignment-1/src/mlruns_iris/148731765894909086/2d79fa245df64f488ffbd8de86683e6b/artifacts
end_time: 1758140224236
entry_point_name: ''
experiment_id: '148731765894909086'
lifecycle_stage: active
run_id: 2d79fa245df64f488ffbd8de86683e6b
run_name: KNN
source_name: ''
source_type: 4
source_version: ''
start_time: 1758140220193
status: 3
tags: []
user_id: Home
