artifact_uri: file:///C:/Users/Home/PycharmProjects/Basic projects/mlops-assignment-1/src/mlruns_iris/148731765894909086/e65d78a591d848528fcc6c7cab6aba69/artifacts
end_time: 1758140436528
entry_point_name: ''
experiment_id: '148731765894909086'
lifecycle_stage: active
run_id: e65d78a591d848528fcc6c7cab6aba69
run_name: Logistic_Regression
source_name: ''
source_type: 4
source_version: ''
start_time: 1758140430260
status: 3
tags: []
user_id: Home
