artifact_uri: file:///C:/Users/Home/PycharmProjects/Basic projects/mlops-assignment-1/src/mlruns_iris/148731765894909086/c360f795ab2749188208faa92aed5fb3/artifacts
end_time: 1758140761388
entry_point_name: ''
experiment_id: '148731765894909086'
lifecycle_stage: active
run_id: c360f795ab2749188208faa92aed5fb3
run_name: KNN
source_name: ''
source_type: 4
source_version: ''
start_time: 1758140757288
status: 3
tags: []
user_id: Home
