artifact_uri: file:///C:/Users/Home/PycharmProjects/Basic projects/mlops-assignment-1/src/mlruns_iris/148731765894909086/3355a70ae9be44f5856541691dd883d0/artifacts
end_time: 1758140284346
entry_point_name: ''
experiment_id: '148731765894909086'
lifecycle_stage: active
run_id: 3355a70ae9be44f5856541691dd883d0
run_name: Logistic_Regression
source_name: ''
source_type: 4
source_version: ''
start_time: 1758140278946
status: 3
tags: []
user_id: Home
