artifact_uri: file:///C:\Users\Home\PycharmProjects\Basic projects\mlops-assignment-1\mlruns_individual/0/38419bb394894bddb67d07b13181ceca/artifacts
end_time: 1758173933134
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 38419bb394894bddb67d07b13181ceca
run_name: register_best_model_enhanced
source_name: ''
source_type: 4
source_version: ''
start_time: 1758173923262
status: 3
tags: []
user_id: Home
