aliases: []
creation_timestamp: 1758173933036
current_stage: None
deployment_job_state: null
description: null
last_updated_timestamp: 1758173933036
metrics: null
model_id: m-998ffb0906554a739459e4bc8cc421c8
name: iris_classifier
params: null
run_id: 38419bb394894bddb67d07b13181ceca
run_link: null
source: models:/m-998ffb0906554a739459e4bc8cc421c8
status: READY
status_message: null
storage_location: file:///C:\Users\Home\PycharmProjects\Basic projects\mlops-assignment-1\mlruns_individual/0/models/m-998ffb0906554a739459e4bc8cc421c8/artifacts
user_id: null
version: 2
