artifact_location: file:///C:/Users/Home/PycharmProjects/Basic projects/mlops-assignment-1/src/mlruns_iris/148731765894909086
creation_time: 1758139883081
experiment_id: '148731765894909086'
last_update_time: 1758139883081
lifecycle_stage: active
name: iris_models
