artifact_location: file:///C:\Users\Home\PycharmProjects\Basic projects\mlops-assignment-1\mlruns_individual/952358615834954900
creation_time: 1758171055073
experiment_id: '952358615834954900'
last_update_time: 1758171055073
lifecycle_stage: active
name: iris_models_individual
