artifact_location: file:///C:/Users/Home/PycharmProjects/Basic projects/mlops-assignment-1/src/mlruns_iris/0
creation_time: 1758139883063
experiment_id: '0'
last_update_time: 1758139883063
lifecycle_stage: active
name: Default
