artifact_uri: file:///C:/Users/Home/PycharmProjects/Basic projects/mlops-assignment-1/src/mlruns_iris/148731765894909086/e94ce9c8a7cb4d1bbedf0582d95b7380/artifacts
end_time: 1758140753484
entry_point_name: ''
experiment_id: '148731765894909086'
lifecycle_stage: active
run_id: e94ce9c8a7cb4d1bbedf0582d95b7380
run_name: Logistic_Regression
source_name: ''
source_type: 4
source_version: ''
start_time: 1758140746882
status: 3
tags: []
user_id: Home
