artifact_uri: file:///C:/Users/Home/PycharmProjects/Basic projects/mlops-assignment-1/src/mlruns_iris/148731765894909086/a06a0dd1a7a14ab5b9a2499d41e160c8/artifacts
end_time: 1758140757276
entry_point_name: ''
experiment_id: '148731765894909086'
lifecycle_stage: active
run_id: a06a0dd1a7a14ab5b9a2499d41e160c8
run_name: SVM
source_name: ''
source_type: 4
source_version: ''
start_time: 1758140753500
status: 3
tags: []
user_id: Home
