artifact_uri: file:///C:/Users/Home/PycharmProjects/Basic projects/mlops-assignment-1/src/mlruns_iris/148731765894909086/8de96463f1064da5b117ff78ee21f3c2/artifacts
end_time: 1758140287717
entry_point_name: ''
experiment_id: '148731765894909086'
lifecycle_stage: active
run_id: 8de96463f1064da5b117ff78ee21f3c2
run_name: SVM
source_name: ''
source_type: 4
source_version: ''
start_time: 1758140284359
status: 3
tags: []
user_id: Home
