artifact_uri: file:///C:/Users/Home/PycharmProjects/Basic projects/mlops-assignment-1/src/mlruns_iris/148731765894909086/038a829fecfb47499be2e96b74f50c68/artifacts
end_time: 1758140332217
entry_point_name: ''
experiment_id: '148731765894909086'
lifecycle_stage: active
run_id: 038a829fecfb47499be2e96b74f50c68
run_name: SVM
source_name: ''
source_type: 4
source_version: ''
start_time: 1758140328695
status: 3
tags: []
user_id: Home
