artifact_location: file:///C:\Users\Home\PycharmProjects\Basic projects\mlops-assignment-1\mlruns_individual/0
creation_time: 1758171055054
experiment_id: '0'
last_update_time: 1758171055054
lifecycle_stage: active
name: Default
