artifact_uri: file:///C:/Users/Home/PycharmProjects/Basic projects/mlops-assignment-1/src/mlruns_iris/148731765894909086/78a53537f83f4173a9c182e34056c5aa/artifacts
end_time: 1758139888733
entry_point_name: ''
experiment_id: '148731765894909086'
lifecycle_stage: active
run_id: 78a53537f83f4173a9c182e34056c5aa
run_name: Logistic_Regression
source_name: ''
source_type: 4
source_version: ''
start_time: 1758139883314
status: 3
tags: []
user_id: Home
