artifact_uri: file:///C:/Users/Home/PycharmProjects/Basic projects/mlops-assignment-1/src/mlruns_iris/148731765894909086/e62931d57d6b41a7bbdd762b2581203b/artifacts
end_time: 1758140291150
entry_point_name: ''
experiment_id: '148731765894909086'
lifecycle_stage: active
run_id: e62931d57d6b41a7bbdd762b2581203b
run_name: KNN
source_name: ''
source_type: 4
source_version: ''
start_time: 1758140287730
status: 3
tags: []
user_id: Home
